# Generated by Django 4.0.2 on 2022-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('activida', models.CharField(max_length=100)),
            ],
        ),
    ]
