# Generated by Django 4.0.2 on 2022-02-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0003_alter_cupon_usado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cupon',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
